package com.cjeg.web.admin.mapper;

import com.cjeg.web.admin.model.UserMenu;
import com.cjeg.web.admin.model.UserMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbg.generated
     */
    long countByExample(UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbg.generated
     */
    int deleteByExample(UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbg.generated
     */
    int insert(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbg.generated
     */
    int insertSelective(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbg.generated
     */
    List<UserMenu> selectByExample(UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMenu record, @Param("example") UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMenu record, @Param("example") UserMenuExample example);
}