package com.cjeg.web.admin.mapper;

import com.cjeg.web.admin.model.Zhang;
import com.cjeg.web.admin.model.ZhangExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    long countByExample(ZhangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    int deleteByExample(ZhangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    int insert(Zhang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    int insertSelective(Zhang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    List<Zhang> selectByExample(ZhangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    Zhang selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Zhang record, @Param("example") ZhangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Zhang record, @Param("example") ZhangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Zhang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhang
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Zhang record);
}